#!/bin/bash 
# 使用 pip 安装所需库
echo 安装组件
python3 -m pip install --upgrade pip          --trusted-host https://repo.huaweicloud.com -i https://repo.huaweicloud.com/repository/pypi/simple
python3 -m pip install --upgrade ttkthemes    --trusted-host https://repo.huaweicloud.com -i https://repo.huaweicloud.com/repository/pypi/simple
python3 -m pip install --upgrade pyautogui    --trusted-host https://repo.huaweicloud.com -i https://repo.huaweicloud.com/repository/pypi/simple
python3 -m pip install --upgrade keyboard     --trusted-host https://repo.huaweicloud.com -i https://repo.huaweicloud.com/repository/pypi/simple
echo 执行完成
# 建立软链接
ln -s /opt/apps/com.gitee.uengine.runner.spark/files/uengine-runner                   /usr/bin/uengine-runner
ln -s /opt/apps/com.gitee.uengine.runner.spark/files/uengine-apk-builder              /usr/bin/uengine-apk-builder
ln -s /opt/apps/com.gitee.uengine.runner.spark/files/uengine-app-uninstall            /usr/bin/uengine-app-uninstall
ln -s /opt/apps/com.gitee.uengine.runner.spark/files/uengine-app-install              /usr/bin/uengine-app-install
ln -s /opt/apps/com.gitee.uengine.runner.spark/files/uengine-clean                    /usr/bin/uengine-clean
ln -s /opt/apps/com.gitee.uengine.runner.spark/files/uengine-runner-about             /usr/bin/uengine-runner-about
ln -s /opt/apps/com.gitee.uengine.runner.spark/files/uengine-keyboard                 /usr/bin/uengine-keyboard
ln -s /opt/apps/com.gitee.uengine.runner.spark/files/uengine-useadb                   /usr/bin/uengine-useadb
ln -s /opt/apps/com.gitee.uengine.runner.spark/files/uengine-runner-launch.sh         /usr/bin/uengine-runner-launch.sh
ln -s /opt/apps/com.gitee.uengine.runner.spark/files/uengine-runner-update-bug        /usr/bin/uengine-runner-update-bug
ln -s /opt/apps/com.gitee.uengine.runner.spark/files/root-uengine                     /usr/bin/uengine-root
ln -s /opt/apps/com.gitee.uengine.runner.spark/files/AutoShell/main.py                /usr/bin/uengine-runner-auto-install-bash
ln -s /opt/apps/com.gitee.uengine.runner.spark/files/uengine-runner-applist-launch.sh /usr/bin/uengine-runner-applist-launch.sh
# 移除安装错误的 UEngine Ubuntu 补丁
which uengine
if [[ $? != 0 ]] && [[ -f /usr/bin/uengine-loading-ubuntu ]]; then
    echo 移除错误的 UEngine Ubuntu 补丁
    # 移除补丁
    rm /usr/share/applications/uengine-loading-ubuntu.desktop
    rm /etc/xdg/autostart/uengine-loading-ubuntu.desktop
    rm /usr/bin/uengine-loading-ubuntu
    for username in $(ls /home)  
    do
        echo /home/$username
        rm /home/$username/uengine-launch/run_daemon.sh
    done
fi
# 更新 uengine-loading-ubuntu（如果存在）
if [[ -f /usr/bin/uengine-loading-ubuntu ]]; then
    echo 更新 uengine-loading-ubuntu
    if [ -f /tmp/upgrade-uengine-loading-ubuntu ]; then
        rm /tmp/upgrade-uengine-loading-ubuntu
    fi
    # 下载新版
    aria2c -x 16 -s 16 -d /tmp -o upgrade-uengine-loading-ubuntu https://code.gitlink.org.cn/gfdgd_xi/uengine-installer-bak/raw/branch/master/run_daemon.sh
    if [ $? == 0 ]; then
        # 替换
        cp /tmp/upgrade-uengine-loading-ubuntu /usr/bin/uengine-loading-ubuntu
        chmod 755 /usr/bin/uengine-loading-ubuntu
        for username in $(ls /home)  
        do
            echo /home/$username
            cp /usr/bin/uengine-loading-ubuntu /home/$username/uengine-launch/run_daemon.sh
            chmod 755 /home/$username/uengine-launch/run_daemon.sh
        done
    fi
    rm /tmp/upgrade-uengine-loading-ubuntu
fi
# 刷新图标缓存
# 因为 Ubuntu 的问题，省略
gtk-update-icon-cache /usr/share/icons/bloom > /dev/null | true
# 向服务器返回安装数加1（不显示内容且忽略错误）
python3 /opt/apps/com.gitee.uengine.runner.spark/files/Download.py 2.1.0 > /dev/null | true
